name: Build MoneySweeper App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            gradlew.bat jlink
          else
            ./gradlew jlink
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtime-${{ matrix.os }}
          path: build/image