name: Build MoneySweeper App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gradle-command: [./gradlew, ./gradlew, gradlew.bat]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ${{ matrix.gradle-command }} jlink

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtime-${{ matrix.os }}
          path: build/image